# Generated by Django 5.0.6 on 2024-08-22 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_user', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, default='')),
                ('profile_img', models.ImageField(default='blank-profile-picture.png', upload_to='profile_image')),
                ('address', models.CharField(blank=True, default='', max_length=90)),
                ('user', models.ForeignKey(max_length=90, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
