# Generated by Django 5.0.6 on 2024-08-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0002_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='post_image'),
        ),
    ]
